### ISSUE TITLE
about the fps during training

### ISSUE THREAD

**Issue by xiangweifeng** [alimama-creative/M3DDM-Video-Outpainting#3]
hi， Fan，
During the trainning, you have said that sample video frames with different frames per second (fps). I guess the pipline as bellows:
(1) extract 16 global frames from the video;
(2) extract F local Frames with a random start-index and a fixed interval which computed by a random fps.

I wonder the fps. In the paper, the fps is selected from [1, 30]. Suppose the origin fps is 30, If we donnot use the video interpolation, we can only extract frames with interval 1,2,3....So that the corresponding fps is 30, 15, 10, 7.5....respectively. If we give a fps with 22, the interval is bigger than 1 but smaller than 2, how to achieve it?

**Comment by fanfanda** [comment]
Your understanding of the steps is correct. For the frames per second (fps) sampled during the training process, if we cannot extract precise frames from the current video to meet the selected_fps, we adopt an approximate strategy. The pseudocode is as follows:
```python
selected_fps = random.randint(rand_fps_range[0], rand_fps_range[1])
selected_fps = min(selected_fps, origin_fps)
selected_frame_interval = round(origin_fps / selected_fps)
```

**Comment by xiangweifeng** [comment]
> Your understanding of the steps is correct. For the frames per second (fps) sampled during the training process, if we cannot extract precise frames from the current video to meet the selected_fps, we adopt an approximate strategy. The pseudocode is as follows:
> 
> ```python
> selected_fps = random.randint(rand_fps_range[0], rand_fps_range[1])
> selected_fps = min(selected_fps, origin_fps)
> selected_frame_interval = round(origin_fps / selected_fps)
> ```

Thank you very much !
does it mean the fps that is used to embed in the unet would be changed as the approximate fps?

**Comment by fanfanda** [comment]
We do not use approximate fps, instead, we directly input the selected_fps embed into the UNet.
