### ISSUE TITLE
Evaluation Metrics

### ISSUE THREAD

**Issue by yuemingPAN** [alimama-creative/M3DDM-Video-Outpainting#6]
Hello, 

Thanks for your great work, your contributions have truly impressed me! I read your paper and have some questions about evaluation. I'm curious about whether the FVD, PSNR, LPIPS metrics are calculated across the entire 256x256 region or only within the outpainted region.  

Thanks! Any clarification you could provide would be sincerely appreciated.

**Comment by Levishery** [comment]
Hello! Do you have the answer?
