### ISSUE TITLE
the global video clip masks

### ISSUE THREAD

**Issue by xiangweifeng** [alimama-creative/M3DDM-Video-Outpainting#9]
Hi, Fan,
for example, the global video is compsed by frame 1,4,8,12; the current video clip is composed by 1, 2, 3, 4. The 1 and 4 should adopt same masks. The 8 and 12 are raw frames, or need to be masked as the current video clip?

**Comment by xiangweifeng** [comment]
another question, in 3.2.1, "In order to construct the training samples for video outpainting, we randomly mask out the edges of each frame.". does it means in a video clip, the mask for each frame is different? or the whole video clip adopt same masks?

**Comment by fanfanda** [comment]
> Hi, Fan, for example, the global video is compsed by frame 1,4,8,12; the current video clip is composed by 1, 2, 3, 4. The 1 and 4 should adopt same masks. The 8 and 12 are raw frames, or need to be masked as the current video clip?

The 8th and 12th need to be masked as the current video clip.

**Comment by fanfanda** [comment]
> Hi, Fan, for example, the global video is compsed by frame 1,4,8,12; the current video clip is composed by 1, 2, 3, 4. The 1 and 4 should adopt same masks. The 8 and 12 are raw frames, or need to be masked as the current video clip?

The 8th and 12th need to be masked as the current video clip.

**Comment by fanfanda** [comment]
> another question, in 3.2.1, "In order to construct the training samples for video outpainting, we randomly mask out the edges of each frame.". does it means in a video clip, the mask for each frame is different? or the whole video clip adopt same masks?

The whole video clip adopts the same masks and some frames are not masked.
